[project]
name = "e-commerce-crawler"
version = "0.1.0"
description = "Web crawler to fetch product url from e-commerce website using href and sitemaps"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "beautifulsoup4>=4.13.3",
]
